[package]
name = "side-effects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_fundsp = "0.3.0"
fundsp = "0.12.0"
rand = "0.8.5"

